project_id = "lktjgfvtujkvlokmgfho"

[functions.bootstrap-admin]
verify_jwt = false

[functions.admin-create-client]
verify_jwt = true

[functions.admin-update-client]
verify_jwt = true

[functions.admin-delete-client]
verify_jwt = true