// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lktjgfvtujkvlokmgfho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrdGpnZnZ0dWprdmxva21nZmhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODUzODQsImV4cCI6MjA2MzM2MTM4NH0.qr6LEAL1BDDiC2DTGcgOo_jsXXT3BwuqTd8n_2nh6x8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);